server:
  port: 8082

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: zookeeper-client
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: false