server:
  port: 9001

spring:
  application:
    name: zookeeper-server
  cloud:
    zookeeper:
      connect-string: localhost:2180
      discovery:
        enabled: true
        register: true  #表示会去注册中心注册服务