#集群配置
clusterServersConfig:
#  idleConnectionTimeout: 10000
#  pingTimeout: 1000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  failedSlaveReconnectionInterval: 3000
#  failedSlaveCheckInterval: 3
##  password: admin
#  subscriptionsPerConnection: 5
#  clientName: "cluster"
#  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#  slaveSubscriptionConnectionMinimumIdleSize: 1
#  slaveSubscriptionConnectionPoolSize: 50
#  slaveConnectionMinimumIdleSize: 32
#  slaveConnectionPoolSize: 64
#  masterConnectionMinimumIdleSize: 32
#  masterConnectionPoolSize: 64
#  readMode: "SLAVE"
  nodeAddresses:
  - "redis://172.19.0.2:6379"
  - "redis://172.19.0.3:6379"
  - "redis://172.19.0.4:6379"
  - "redis://172.19.0.5:6379"
  - "redis://172.19.0.6:6379"
  - "redis://172.19.0.7:6379"
#  scanInterval: 1000

threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"
