server:
  port: 9006

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: zookeeper-client
  cloud:
    zookeeper:
      connect-string: localhost:2180
      discovery:
        enabled: true
        register: false