
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wojiaolds
    password: lds1992
  redis:
    host: localhost
    port: 6379
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    type: redis

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/html/
  mvc:
    favicon:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

  server:
    port: 8081
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:log/logback-spring.xml
