spring:
  cloud:
    stream:
      binders:
        test:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: localhost
                port: 5672
                username: guest
                password: guest

      bindings:
        input1:
          destination: testRabbit
          content-type: application/json
          default-binder: test
          group: average
        output1:
          destination: testRabbit
          content-type: application/json
          default-binder: test
        input2:
          destination: testRabbit
          content-type: application/json
          default-binder: test
          group: average1
        input3:
          destination: testRabbit1
          content-type: application/json
          default-binder: test
          group: average1
        output2:
          destination: testRabbit1
          content-type: application/json
          default-binder: test
#所有订阅指定topics的组都会收到发布数据的一份副本，但是每一个组内只有一个成员会收到该消息
#input1跟input2，input3属于不同的消费者组，所以这两个消费者租都会收到消息，
#但是input2，input3只会有一个成员收到消息